version: '3.7'
services:
    server_core:
        container_name: server_core
        build:
            context: .  # context set to repo root
            target: server_core
        entrypoint: [/app/server_core, --logfile]
        environment:
            - GEN2MODULEIP=atserver
        volumes:
            - ./logs:/app/logs
        networks:
            internal:
                aliases:
                    - srvcore
    mgr_service:
        container_name: mgr_service
        build:
            context: .  # context set to repo root
            target: service_mgr
        entrypoint: [/app/service_mgr, --uds, /app/uds.sock, --vssPathList, vsspathlist.json, --logfile]
        depends_on:
            - "server_core"
        volumes:
            - ./logs:/app/logs
        environment:
            - GEN2MODULEIP=srvcore
        networks:
            internal:
                aliases:
                    - servicemgr         
    server_at:
        container_name: server_at
        build:
            context: .  # context set to repo root
            target: at_server
        entrypoint: [/app/at_server, --logfile]
        depends_on:
            - "server_core"
        volumes:
            - ./logs:/app/logs
        environment:
            - GEN2MODULEIP=srvcore
        ports:
            - "8600:8600"
        networks:
            internal:
                aliases:
                    - atserver
            external:
                aliases:
                    - atserver
    server_agt:
        container_name: server_agt
        build:
            context: .  # context set to repo root
            target: agt_server
        entrypoint: [/app/agt_server, --logfile]
        depends_on:
            - "server_core"
        volumes:
            - ./logs:/app/logs
        environment:
            - GEN2MODULEIP=srvcore
        ports:
            - "7500:7500"
        networks:
            internal:
                aliases:
                    - agtserver
            external:
                aliases:
                    - agtserver
    mgr_http:
        container_name: mgr_http
        build:
            context: .  # context set to repo root
            target: http_mgr
        entrypoint: [/app/http_mgr, --logfile]
        working_dir: /app
        depends_on:
            - "server_core"
            - "mgr_ws"
        volumes:
            - ./logs:/app/logs
        ports:
            - "8888:8888"
            - "444:444"
        environment:
            - GEN2MODULEIP=srvcore
        networks:
            - internal
            - external
    mgr_ws:
        container_name: mgr_ws
        build:
            context: .  # context set to repo root
            target: ws_mgr
        entrypoint: [/app/ws_mgr, --logfile]
        depends_on:
            - "server_core"
        volumes:
            - ./logs:/app/logs
        environment:
            - GEN2MODULEIP=srvcore
        ports:
            - "8080:8080"
            - "443:443"
        networks:
            - internal
            - external
    mgr_mqtt:
        container_name: mgr_mqtt
        build:
            context: .  # context set to repo root
            target: mqtt_mgr
        entrypoint: [/app/mqtt_mgr, --logfile]
        depends_on:
            - "server_core"
        volumes:
            - ./logs:/app/logs
        environment:
            - GEN2MODULEIP=srvcore
        ports: 
            - "1883:1883"
        networks:
            - internal
            - external
    tls_client:
        container_name: tls_client
        build:
            context: .  # context set to repo root
            target: tls_client
        networks:
            - external
    server_web:
        container_name: server_web
        image: 'httpd:2.4.48-buster'
        depends_on:
            - "server_core"
        volumes:
            - ./client/client-1.0/Javascript/:/usr/local/apache2/htdocs/
        ports:
            - "10080:80"
        networks:
            - external
networks:
    internal:
    external: